#!/bin/bash
rm KoleCell\[0].apic\[51]-batch.sbatch
rm KoleCell\[0].apic\[52]-batch.sbatch
rm KoleCell\[0].apic\[53]-batch.sbatch
rm KoleCell\[0].apic\[54]-batch.sbatch
rm KoleCell\[0].apic\[55]-batch.sbatch
rm KoleCell\[0].apic\[56]-batch.sbatch
rm KoleCell\[0].apic\[57]-batch.sbatch
rm KoleCell\[0].apic\[58]-batch.sbatch
rm KoleCell\[0].apic\[59]-batch.sbatch
rm KoleCell\[0].apic\[5]-batch.sbatch
rm KoleCell\[0].apic\[60]-batch.sbatch
rm KoleCell\[0].apic\[61]-batch.sbatch
rm KoleCell\[0].apic\[62]-batch.sbatch
rm KoleCell\[0].apic\[63]-batch.sbatch
rm KoleCell\[0].apic\[64]-batch.sbatch
rm KoleCell\[0].apic\[65]-batch.sbatch
rm KoleCell\[0].apic\[66]-batch.sbatch
rm KoleCell\[0].apic\[67]-batch.sbatch
rm KoleCell\[0].apic\[68]-batch.sbatch
rm KoleCell\[0].apic\[69]-batch.sbatch
rm KoleCell\[0].apic\[6]-batch.sbatch
rm KoleCell\[0].apic\[70]-batch.sbatch
rm KoleCell\[0].apic\[71]-batch.sbatch
rm KoleCell\[0].apic\[72]-batch.sbatch
rm KoleCell\[0].apic\[73]-batch.sbatch
rm KoleCell\[0].apic\[74]-batch.sbatch
rm KoleCell\[0].apic\[75]-batch.sbatch
rm KoleCell\[0].apic\[76]-batch.sbatch
rm KoleCell\[0].apic\[77]-batch.sbatch
rm KoleCell\[0].apic\[78]-batch.sbatch
rm KoleCell\[0].apic\[79]-batch.sbatch
rm KoleCell\[0].apic\[7]-batch.sbatch